---
- hosts: Workers
  become: true
  tasks:
    - name: Install Kubernetes packages
      apt:
        name: 
          - kubelet
          - kubeadm
        state: present
        update_cache: yes

    - name: Mark Kubernetes packages on hold
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
...