---
- hosts: Master
  become: true
  tasks:
    - name: Install Kubernetes packages
      apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Mark Kubernetes packages on hold
      dpkg_selections:
        name: "{{ item }}"
        selection: hold
      loop:
        - kubelet
        - kubeadm
        - kubectl

    - name: Pull Kubernetes container images
      shell: kubeadm config images pull >> /home/ubuntu/image_pull.txt
      args:
        chdir: /home/ubuntu
        creates: image_pull.txt

    - name: Initialize Kubernetes cluster
      shell: kubeadm init >> /home/ubuntu/cluster.txt
      args:
        chdir: /home/ubuntu
        creates: cluster.txt 

    - name: Create .kube directory
      file:
        path: "/home/ubuntu/.kube"
        state: directory
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0700'

    - name: Copy admin.conf to user's home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/ubuntu/.kube/config"
        remote_src: true
        owner: "ubuntu"
        group: "ubuntu"
        mode: '0600'

    - name: Install Pod Network
      become_user: ubuntu
      shell: kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml >> /home/ubuntu/pod_setup.txt
      args:
        chdir: /home/ubuntu
        creates: pod_setup.txt
...